#### DRIVER SCRIPT TO RUN ALL ANALYSES
source("microbiome_functions.R")
source("Load_data.R")
source("taxonomy_processing.R")
source("decontam_16S.R")
source("decontam_RNA.R")
source("decontam_WGS.R")
source("Fig1_Nov2024.R")
source("Fig2_Nov2024.R")
source("Fig3_Nov2024.R")
source("Fig4_Nov2024.R")
source("supplemental_figures_v2.R")
source("write_tables.R")
source("nejman_weizmann_dataAnalysis.R")
